Rip out network-based update proxy remanents
QubesOS/qubes-core-agent-linux pull request #377
Opened 2022-04-21 15:57 UTC by DemiMarie

732e9d02eeae18c3cfe3c10beceed1564f28c399 removed most of the network-based updates proxy, but it didn't change the SysV init scripts.

2022-05-04 01:50 UTC, marmarek requested changes

2022-05-04 01:50 UTC, marmarek commented on vm-init.d/qubes-updates-proxy
>      /sbin/iptables -I INPUT -i vif+ -p tcp --dport 8082 -j ACCEPT
I think this line (and the matching one on stop) is not necessary either. The proxy is accessed over 'lo', not 'vif' interface.

2022-05-05 08:23 UTC, DemiMarie commented
PipelineRetry

2022-05-12 01:47 UTC, marmarek approved these changes

2022-05-12 03:20 UTC, merged