Add purging of no longer allowed connections from conntrack
QubesOS/qubes-core-agent-linux pull request #399
Opened 2022-12-12 06:37 UTC by mati7337

Previously adding a firewall rule didn't close already established connections: https://github.com/QubesOS/qubes-issues/issues/4141

2022-12-13 07:02 UTC, marmarek requested changes
Tests need an update. In existing tests you can just mock this call and ignore it, but add a test checking this functionality specifically - at the very least unit tests for functions you add.

2022-12-14 14:21 UTC, mati7337 commented on qubesagent/firewall.py
> +        subprocess.Popen(['conntrack', '-D', '--src', src, '--dst', con[1],
Changed it to `.run` as it doesn't raise an exception if exit code is non-zero. `.check_call` would raise an exception if connection dies in between `conntrack -L` and `conntrack -D`.

2022-12-14 14:24 UTC, mati7337 commented
I also changed `ip_network(rule[f'dst{family}'])` to `ip_network(rule[f'dst{family}'], False)` so it doesn't raise an exception if the host bits are set (`qvm-firewall` allows it).

2022-12-16 13:40 UTC, marmarek commented
PipelineRetry

2022-12-16 16:04 UTC, marmarek commented on qubesagent/firewall.py
> +                print(line)
This line wants removing, but I can do that post-merge.

2022-12-16 16:04 UTC, marmarek approved these changes

2022-12-16 16:04 UTC, marmarek approved these changes

2022-12-16 16:41 UTC, merged