Use network-pre.target to order firewall before network uplink
QubesOS/qubes-core-agent-linux pull request #432
Opened 2023-05-31 21:07 UTC by DemiMarie

network-pre.target is intended to be ordered after any service that sets up a firewall and before any service that enables networking. Therefore, have network-pre.target require qubes-antispoof.service (unconditionally) and qubes-iptables.service (only if qubes-iptables.service is enabled).  qubes-network-uplink@.service now has Requires= and After= dependencies on network-pre.target, so it is ordered after both Qubes and third-party firewall rules.

2023-06-30 15:03 UTC, marmarek commented
there is a file conflict

2023-07-01 13:52 UTC, marmarek requested changes

2023-07-01 13:52 UTC, marmarek commented on vm-systemd/network-pre.target.d/30_qubes.conf
> +After=qubes-antispoof.service
I think it's better to add them to the `qubes-antispoof.service` instead (as `RequiredBy=` and `Before=` respectively).

2023-07-03 12:04 UTC, marmarek commented
Does this by a chance helps with https://github.com/QubesOS/qubes-issues/issues/8305 too?

2023-07-03 12:10 UTC, marmarek approved these changes

2023-07-03 16:22 UTC, DemiMarie commented
> Does this by a chance help with [QubesOS/qubes-issues#8305](https://github.com/QubesOS/qubes-issues/issues/8305) too?

I have not checked, but I would not at all be surprised either, since it removes the dependency on `sys-subsystem-net-device-%i.device`.

2023-07-03 20:00 UTC, DemiMarie commented
> Does this by a chance help with [QubesOS/qubes-issues#8305](https://github.com/QubesOS/qubes-issues/issues/8305) too?

It does indeed!  At first I thought it did not, but that turned out to be a case of PEBKAC.

2023-07-04 01:43 UTC, merged