Set correct SELinux contexts on /rw
QubesOS/qubes-core-agent-linux pull request #437
Opened 2023-07-01 01:46 UTC by DemiMarie

This is needed for disposable sys-net to work properly.  Without it /rw is not labeled correctly, causing SELinux to (correctly) block NetworkManager's writes to /rw/config/NM-system-connections.

Fixes: QubesOS/qubes-issues#8242

2023-07-01 03:05 UTC, marmarek commented
Isn't it better to simply make `qubes-relabel-rw.service` working in DispVM too (drop its condition on persistence)?

2023-07-02 00:16 UTC, DemiMarie commented
> Isn't it better to simply make `qubes-relabel-rw.service` working in DispVM too (drop its condition on persistence)?

yes, but it is also better to create the files with the correct contexts in the first place.

2023-07-02 01:33 UTC, marmarek commented
In that case, `network/network-manager-prepare-conf-dir` may need adjustment too.

BTW, shellcheck complains.

2023-08-03 14:49 UTC, marmarek commented
ping?

2023-08-03 16:29 UTC, DemiMarie commented
fixed, assuming shellcheck is smart enough to note that `${SOMEVAR:+-Z}` without quoting is perfectly safe.

2023-08-05 02:20 UTC, marmarek requested changes

2023-08-05 02:20 UTC, marmarek commented on init/functions
> +                mkdir "${enable_selinux+-Z}" -- "$home_root/$homedirwithouthome" || return 73
Why splitting this into two mkdir calls (for which you needed to split this into two branches and extra pattern matching)? If you want this to fail if directory already exists, there is no point in that - this part is under `if ! test -d "$home_root/$homedirwithouthome"` (and this script doesn't really need to worry about racing against anything else accessing `/rw`).
But if there is some other reason, please explain it in the commit message.

2023-08-05 02:20 UTC, marmarek commented on init/setup-rw.sh
> +    unset enable_selinux
The unset isn't really necessary, if you set it unconditionally anyway.

2023-08-05 02:20 UTC, marmarek commented on init/setup-rw.sh
> +        if [ -n "$enable_selinux" ]; then restorecon -RF /rw/config; fi
`qubes-relabel-rw.service` (which is now also enabled in DispVMs) will do that again. if `restorecon` is called here (and in few other cases below), maybe create `/rw/.autorelabel` too (which BTW is misnamed...).

2023-08-07 20:38 UTC, marmarek approved these changes
I'll regret accepting this blown up mkdir but okay...

2023-08-07 21:06 UTC, merged