Misc-post-stop: remove unused QubesIncoming
QubesOS/qubes-core-agent-linux pull request #515
Opened 2024-07-22 11:32 UTC by kennethrrosen

resolves QubesOS/qubes-issues#8307

2024-07-22 11:42 UTC, alimirjamali approved these changes

2024-07-22 13:42 UTC, kennethrrosen commented
> Can you please cleanup the git history here - include just the last commit?

@marmarek done

2024-07-22 14:17 UTC, kennethrrosen commented
I've made a minor change based on a discussion in the forum: https://forum.qubes-os.org/t/github-issue-8307-automatically-clean-up-qubesincoming-directory-if-empty/27798/14

2024-08-08 00:40 UTC, marmarek requested changes
Besides comments below, typo in the commit message (`reaolves`)

2024-08-08 00:40 UTC, marmarek commented on vm-systemd/misc-post-stop.sh
> +if [ -d /home/user/QubesIncomming ]; then
```suggestion
if [ -d /home/user/QubesIncoming ]; then
```

And also don't hardcode `user`. See for example `qubes-rpc/qubes.WaitForSession` how to get the user name.

2024-08-08 00:40 UTC, marmarek commented on vm-systemd/misc-post-stop.sh
> +    find /home/user/QubesIncoming -mindepth 1 -type d -empty -delete
Save the path (with the above adjustments) in a variable to not repeat it each time?

2024-08-08 17:55 UTC, rustybird commented
Sorry for chiming in late. I had assumed that this functionality is intended to be optional (opt-in or opt-out) but it looks like it's always-on. Isn't the effect a bit intense with that in mind?

Deleting `~/QubesIncoming/source-vm/` if it's completely empty seems relatively uncontroversial to me. (Although the reasoning for *not* deleting an empty `~/QubesIncoming/` - vanishing file manager bookmarks - could apply here too for some people's workflows.)

But recursively deleting empty directories at arbitrary depths, and especially empty files, can "randomly" mangle complex directory trees. Like, occasionally I'll move a downloaded tarball or similar (e.g. a software package) from a DispVM to another VM and then leave all the extracted contents lying around for a while, right there inside of `~/QubesIncoming/source-vm/`. These can contain meaningful empty directories or empty marker files.

2024-09-29 21:59 UTC, kennethrrosen commented
@marmarek resolved. gave this some time to let others chime in on the change.

2024-09-29 22:08 UTC, alimirjamali approved these changes

2024-09-29 23:29 UTC, alimirjamali approved these changes

2024-10-04 13:51 UTC, marmarek commented
> deleting empty directories at arbitrary depths, and especially empty files, can "randomly" mangle complex directory trees. Like, occasionally I'll move a downloaded tarball or similar (e.g. a software package) from a DispVM to another VM and then leave all the extracted contents lying around for a while, right there inside of `~/QubesIncoming/source-vm/`. These can contain meaningful empty directories or empty marker files.

This is a valid concern. I'd say removing empty files/dirs directly in `~/QubesIncoming/source-vm/` (and empty `source-vm` itself) should be okay, but going deeper is problematic. And also, an opt-out mechanism would be useful, for example check for `no-qubesincoming-cleanup` qvm-service (skip if `/run/qubes-service/no-qubesincoming-cleanup` is present)

2024-10-04 14:15 UTC, kennethrrosen commented
> and also, an opt-out mechanism would be useful, for example check for `no-qubesincoming-cleanup` qvm-service (skip if `/run/qubes-service/no-qubesincoming-cleanup` is present)

@marmarek I can add
```
# Check for opt-out mechanism
if [ -f /run/qubes-service/no-qubesincoming-cleanup ]; then
    exit 0
fi
```
 And maybe even a note at the top of the script to instruct users on adding their own qubes service until it's added by default in the qube manager GUI? Or I could make a PR for that with some guidance from @alimirjamali

2024-10-04 14:18 UTC, marmarek commented
There is a qvm-service discovery mechanism so it shows up in a dropdown in the qube settings (services tab). See `qubes-rpc/post-install.d/10-qubes-core-agent-features.sh`, you can add there `qvm-features-request supported.service.no-qubesincoming-cleanup=1`

2024-10-04 14:50 UTC, alimirjamali commented
> but going deeper is problematic

This is easily resolvable @kennethrrosen. You could add `--maxdepth 1` to find commands to resolve this.

2024-10-19 20:38 UTC, marmarek approved these changes

2024-10-19 23:03 UTC, merged