Allow logging in to rescue/emergency shell as root
QubesOS/qubes-core-agent-linux pull request #526
Opened 2024-10-31 02:10 UTC by DemiMarie

In Qubes OS guests, the console is _always_ the Xen console.  There are _never_ untrusted entities with access to this under _any_ circumstances.  The only supported way to get access to this from a VM is the admin.vm.Console service, which is (by design) equivalent to root access in the destination VM.

Therefore, set SYSTEMD_SULOGIN_FORCE=1 to tell systemd-sulogin-shell to pass --force to sulogin(8).  Since the root account is locked in Qubes VMs, this causes sulogin(8) to allow login as root without a password.

2024-11-04 13:36 UTC, marmarek commented
Should those drop-ins be included in initramfs (when generated in VM) too? Or maybe they already are there?

2024-11-04 19:41 UTC, DemiMarie commented
> Should those drop-ins be included in initramfs (when generated in VM) too? Or maybe they already are there?

Yes, they should.  Dracut module?

2024-11-06 03:17 UTC, marmarek commented
```
19:36:45 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG: RPM build errors:
19:36:45 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG: error: File not found: /builddir/build/BUILDROOT/qubes-core-agent-4.3.11-1.1.fc40.x86_64/usr/lib/dracut/modules.d/99qubes/module-setup.sh
```

2024-11-06 17:27 UTC, DemiMarie commented
Should this be conditional on the VM _not_ being `sys-usb`?  `sys-usb` might get an untrusted USB serial port plugged into it.

2024-11-06 17:49 UTC, marmarek commented
> Should this be conditional on the VM _not_ being `sys-usb`? `sys-usb` might get an untrusted USB serial port plugged into it.

Similar issue may apply to other VM too. Can you make it specifically for hvc0 console only  instead?

2024-11-06 18:45 UTC, DemiMarie commented
> > Should this be conditional on the VM _not_ being `sys-usb`? `sys-usb` might get an untrusted USB serial port plugged into it.
> 
> But actually does other consoles matter here? Isn't rescue/emergency started only on the primary console (as configured with `console=` kernel param)?

It should be indeed.  I can check.

2024-12-23 01:17 UTC, DemiMarie commented
> > > Should this be conditional on the VM _not_ being `sys-usb`? `sys-usb` might get an untrusted USB serial port plugged into it.
> > 
> > 
> > But actually does other consoles matter here? Isn't rescue/emergency started only on the primary console (as configured with `console=` kernel param)?
> 
> It should be indeed. I can check.

Addressed much more simply by explicitly setting `/dev/hvc0` as the terminal path.

2024-12-24 03:50 UTC, marmarek requested changes

2024-12-24 03:50 UTC, marmarek commented on rpm_spec/core-agent.spec.in
> +omit others.
There is already a bunch of dracut modules in qubes-kernel-vm-support package (linux-utils repo). I'm not suggesting moving it there (but if you want, that is an option too), but to better describe what is in this one, and how is it different from the other one.

2024-12-29 11:40 UTC, marmarek commented
I'd like to have a test for this feature, I can write one, but I need few primitives for it:
- how to break the boot in initramfs stage, preferably without involving the default 2min (?) timeout for rootfs mount
- how to break the boot after initramfs (mask some unit via kernel cmdline? remove some file?)

2024-12-29 21:20 UTC, DemiMarie commented
> I'd like to have a test for this feature, I can write one, but I need few primitives for it:
> 
> * how to break the boot in initramfs stage, preferably without involving the default 2min (?) timeout for rootfs mount

`rd.rescue` or `rd.emergency` on kernel command line with an in-VM kernel.

> * how to break the boot after initramfs (mask some unit via kernel cmdline? remove some file?)

`rescue` or `emergency` on kernel command line, with either dom0-provided or in-VM kernel.

2024-12-30 00:50 UTC, DemiMarie commented
I tested this.

2025-02-13 15:13 UTC, marmarek commented
I've (finally) written a test for this (will open a PR in a moment). Summary of running it:
- works fine with Fedora 41 xfce template and dom0-provided kernel
- is unnecessary with Fedora 41 xfce template and in-vm kernel for emergency mode in initramfs (this one gives shell already, without any of the changes here)
- doesn't work with Debian 12 xfce template (still says "Cannot open access to console, the root account is locked")
- adding `rd.emergency` to kernel cmdline on Debian doesn't trigger emergency shell in initrd at all (with in-vm kernel), so I don't know if it works or if it's necessary

2025-02-13 15:14 UTC, marmarek commented
I haven't ran the test on Whonix yet, I guess results will be similar to Debian.

2025-11-11 19:18 UTC, DemiMarie commented
@marmarek friendly ping

2026-04-07 01:28 UTC, marmarek commented
> @marmarek friendly ping

I don't see any changes here since my last comment describing where it doesn't work...

2026-04-07 03:36 UTC, DemiMarie commented
@marmarek this was probably either on the wrong issue, or me not paying attention.

2026-05-25 01:22 UTC, DemiMarie commented
Closing as I don’t have time to finish this.

2026-05-25 01:22 UTC, closed without merging