SystemD dropins for minimal sys-net and sys-usb
QubesOS/qubes-core-agent-linux pull request #540
Opened 2024-12-21 13:26 UTC by Guiiix

Some unnecessary services are running on sys-net and sys-usb which consumes RAM for nothing. SystemD dropins are added to automatically disable identified unecessary services by enabling minimal-netvm or minimal-usbvm  service on the sys-vms with qvm-service.

2024-12-21 14:49 UTC, marmarek commented
packaging need an update, both RPM and DEB. See CI logs, for example:
```
14:34:27 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG:     Installed (but unpackaged) file(s) found:
14:34:27 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG:    /usr/lib/systemd/user/at-spi-dbus-bus.service.d/30_qubes.conf
14:34:27 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG:    /usr/lib/systemd/user/gvfs-daemon.service.d/30_qubes.conf
14:34:27 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG:    /usr/lib/systemd/user/pipewire.service.d/30_qubes.conf
14:34:27 [qb.build_rpm.core-agent-linux.vm-fc40.build] DEBUG:    /usr/lib/systemd/user/wireplumber.service.d/30_qubes.conf
```

2024-12-27 00:22 UTC, marmarek commented
PipelineRetry

2024-12-27 20:06 UTC, marmarek commented
Pipewire drop-in needs a different name:
```
fedora-41-xfce:err: Transaction test error:
fedora-41-xfce:err:   file /usr/lib/systemd/user/pipewire.service.d/30_qubes.conf conflicts between attempted installs of pipewire-qubes-4.3.4-1.fc41.x86_64 and qubes-core-agent-systemd-4.3.14-1.3.fc41.x86_64
```

2024-12-28 14:25 UTC, marmarek commented
Without polkit(?), the right click nm-applet checkboxes ("enable networking", "enable wifi") don't work...

2024-12-28 15:42 UTC, Guiiix commented
@marmarek this is a mistake. Polkit should be disabled only for minimal sys-usb. Same for Bluetooth.

2025-01-03 03:55 UTC, marmarek commented
I've tested it a bit on Novacustom V56 laptop, and with sys-net set to 300MB wifi quite often crashes (`page allocation failure` in dmesg) after system suspend. In fact, it happens also quite ofen with 350MB too...

2025-02-07 19:12 UTC, marmarek commented
This fails to build - see CI logs

2025-02-09 09:49 UTC, Guiiix commented
Yes, I changed the PR to draft during the build tests. I didn't think you'd get a notification. Now it's good.

- Unnecessary services are disabled
- Some kernel settings are set to prevent memory allocation issues with drivers
- After suspend, we are trying to free some memory by forcefully dropping caches

2025-02-09 19:55 UTC, marmarek requested changes

2025-02-09 19:55 UTC, marmarek commented on vm-systemd/qubes-sysctl-minimal-sys-net.service
> +ConditionPathExists=/var/run/qubes/this-is-netvm
What is the intended effect? Right now it enables it when _both_ conditions are true - so, if it's netvm _and_ the minimal-netvm service is enabled. If you meant to automatically enable it in netvm but also in potentially other if requested, then it should have `|` prefix. But otherwise, I'd prefer a single condition - either just "minimal-netvm" service, or automatic in an netvm.

2025-02-10 01:55 UTC, marmarek commented
And please announce availability of `minimal-netvm` and `minimal-usbvm` services, see `qubes-rpc/post-install.d/10-qubes-core-agent-features.sh`

2025-02-10 02:02 UTC, marmarek commented
I can confirm that now sys-net with 325MB no longer runs into driver failures due to too little memory :) Wifi automatically re-connects after suspend etc.

2025-02-11 20:12 UTC, Guiiix commented
> I can confirm that now sys-net with 325MB no longer runs into driver failures due to too little memory :) Wifi automatically re-connects after suspend etc.

I've been running my sys-net with 300MB for a couple of days and it works too. NM applet is a bit slow but internet connection is stable and I don't see any failure in logs :slightly_smiling_face:

2025-02-13 12:38 UTC, marmarek approved these changes

2025-02-13 12:53 UTC, merged

2025-02-19 10:20 UTC, marmarek commented
Uhm, sys-net just got too aggressive OOM killer:
```
[2025-02-19 05:55:58] [    4.549894] EXT4-fs (xvdb): mounted filesystem cc0de015-4576-48b6-92fd-e92dbc733321 r/w with ordered data mode. Quota mode: none.
[2025-02-19 05:55:58] [    4.694852] cp invoked oom-killer: gfp_mask=0x140dca(GFP_HIGHUSER_MOVABLE|__GFP_COMP|__GFP_ZERO), order=0, oom_score_adj=0
[2025-02-19 05:55:58] [    4.694892] CPU: 1 PID: 427 Comm: cp Not tainted 6.6.77-1.qubes.fc41.x86_64 #1
[2025-02-19 05:55:58] [    4.694914] Hardware name: Xen HVM domU, BIOS 4.19.1 02/16/2025
[2025-02-19 05:55:58] [    4.694933] Call Trace:
[2025-02-19 05:55:58] [    4.694943]  <TASK>
[2025-02-19 05:55:58] [    4.694955]  dump_stack_lvl+0x4d/0x70
[2025-02-19 05:55:58] [    4.694972]  dump_header+0x4a/0x240
[2025-02-19 05:55:58] [    4.694988]  oom_kill_process+0xf7/0x190
[2025-02-19 05:55:58] [    4.695002]  out_of_memory+0xf4/0x330
[2025-02-19 05:55:58] [    4.695015]  __alloc_pages_slowpath.constprop.0+0x55e/0xbc0
[2025-02-19 05:55:58] [    4.695032]  ? __do_sys_brk+0x290/0x3e0
[2025-02-19 05:55:58] [    4.695046]  __alloc_pages+0x320/0x340
[2025-02-19 05:55:58] [    4.695059]  __folio_alloc+0x15/0x30
[2025-02-19 05:55:58] [    4.695071]  vma_alloc_folio+0x9e/0x380
[2025-02-19 05:55:58] [    4.695085]  do_anonymous_page+0x6c/0x3b0
[2025-02-19 05:55:58] [    4.695103]  __handle_mm_fault+0x39b/0x6d0
[2025-02-19 05:55:58] [    4.695117]  handle_mm_fault+0xdd/0x350
[2025-02-19 05:55:58] [    4.695130]  do_user_addr_fault+0x15b/0x630
[2025-02-19 05:55:58] [    4.695145]  exc_page_fault+0x7f/0x180
[2025-02-19 05:55:58] [    4.695159]  asm_exc_page_fault+0x26/0x30
[2025-02-19 05:55:58] [    4.695173] RIP: 0033:0x7b9ebf676fb3
[2025-02-19 05:55:58] [    4.695187] Code: 34 19 49 39 d4 49 89 74 24 60 0f 95 c2 48 29 d8 48 83 c1 10 0f b6 d2 48 83 c8 01 48 c1 e2 02 48 09 da 48 83 ca 01 48 89 51 f8 <48> 89 46 08 e9 aa fe ff ff 48 8d 0d 2d 80 13 00 ba 64 10 00 00 48
[2025-02-19 05:55:58] [    4.695232] RSP: 002b:00007ffccca7b030 EFLAGS: 00010206
[2025-02-19 05:55:58] [    4.695248] RAX: 0000000000006fc1 RBX: 00000000000000d0 RCX: 00005997ce4a8f80
[2025-02-19 05:55:58] [    4.695269] RDX: 00000000000000d1 RSI: 00005997ce4a9040 RDI: 0000000000000000
[2025-02-19 05:55:58] [    4.695289] RBP: 00007ffccca7b080 R08: 00000000000000d0 R09: 0000000000000001
[2025-02-19 05:55:58] [    4.695310] R10: 0000000000000004 R11: 0000000000000000 R12: 00007b9ebf7dfac0
[2025-02-19 05:55:58] [    4.695330] R13: 00000000000000c7 R14: 00000000000000d0 R15: fffffffffffffed8
[2025-02-19 05:55:58] [    4.695354]  </TASK>
[2025-02-19 05:55:58] [    4.695391] Mem-Info:
[2025-02-19 05:55:58] [    4.695401] active_anon:16039 inactive_anon:163 isolated_anon:0
[2025-02-19 05:55:58] [    4.695401]  active_file:9440 inactive_file:5929 isolated_file:0
[2025-02-19 05:55:58] [    4.695401]  unevictable:0 dirty:1002 writeback:1
[2025-02-19 05:55:58] [    4.695401]  slab_reclaimable:2144 slab_unreclaimable:7346
[2025-02-19 05:55:58] [    4.695401]  mapped:5560 shmem:155 pagetables:587
[2025-02-19 05:55:58] [    4.695401]  sec_pagetables:0 bounce:0
[2025-02-19 05:55:58] [    4.695401]  kernel_misc_reclaimable:0
[2025-02-19 05:55:58] [    4.695401]  free:1343 free_pcp:36 free_cma:0
[2025-02-19 05:55:58] [    4.695488] Node 0 active_anon:64156kB inactive_anon:652kB active_file:37760kB inactive_file:23716kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:22240kB dirty:4008kB writeback:4kB shmem:620kB shmem_thp:0kB shmem_pmdmapped:0kB anon_thp:0kB writeback_tmp:0kB kernel_stack:1836kB pagetables:2348kB sec_pagetables:0kB all_unreclaimable? no
[2025-02-19 05:55:58] [    4.695561] Node 0 DMA free:1736kB boost:2048kB min:2176kB low:2208kB high:2240kB reserved_highatomic:0KB active_anon:8404kB inactive_anon:64kB active_file:3208kB inactive_file:740kB unevictable:0kB writepending:0kB present:15992kB managed:15360kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[2025-02-19 05:55:58] [    4.695625] lowmem_reserve[]: 0 201 201 201 201
[2025-02-19 05:55:58] [    4.695641] Node 0 DMA32 free:3636kB boost:2048kB min:3796kB low:4232kB high:4668kB reserved_highatomic:0KB active_anon:55588kB inactive_anon:588kB active_file:34680kB inactive_file:22828kB unevictable:0kB writepending:4012kB present:274428kB managed:205392kB mlocked:0kB bounce:0kB free_pcp:144kB local_pcp:112kB free_cma:0kB
[2025-02-19 05:55:58] [    4.695708] lowmem_reserve[]: 0 0 0 0 0
[2025-02-19 05:55:58] [    4.695721] Node 0 DMA: 3*4kB (UM) 0*8kB 0*16kB 1*32kB (U) 0*64kB 1*128kB (U) 0*256kB 1*512kB (M) 1*1024kB (M) 0*2048kB 0*4096kB = 1708kB
[2025-02-19 05:55:58] [    4.695757] Node 0 DMA32: 231*4kB (UE) 92*8kB (U) 40*16kB (UME) 8*32kB (U) 3*64kB (UE) 1*128kB (M) 1*256kB (M) 1*512kB (M) 0*1024kB 0*2048kB 0*4096kB = 3644kB
[2025-02-19 05:55:58] [    4.695801] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[2025-02-19 05:55:58] [    4.695825] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[2025-02-19 05:55:58] [    4.695848] 15543 total pagecache pages
[2025-02-19 05:55:58] [    4.695860] 0 pages in swap cache
[2025-02-19 05:55:58] [    4.695870] Free swap  = 1048316kB
[2025-02-19 05:55:58] [    4.695881] Total swap = 1048572kB
[2025-02-19 05:55:58] [    4.695894] 72605 pages RAM
[2025-02-19 05:55:58] [    4.695902] 0 pages HighMem/MovableOnly
[2025-02-19 05:55:58] [    4.695912] 17417 pages reserved
[2025-02-19 05:55:58] [    4.695923] 0 pages cma reserved
[2025-02-19 05:55:58] [    4.695934] 0 pages hwpoisoned
[2025-02-19 05:55:58] [    4.695945] Tasks state (memory values in pages):
[2025-02-19 05:55:58] [    4.695958] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[2025-02-19 05:55:58] [    4.695987] [    279]     0   279     3853     1568    73728        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696012] [    283]     0   283     3837     1536    69632        0             0 systemd-userdbd
[2025-02-19 05:55:58] [    4.696036] [    284]     0   284    17460      704    57344        0             0 qubesdb-daemon
[2025-02-19 05:55:58] [    4.696060] [    286]     0   286     3976     1696    73728        0             0 systemd-userwor
[2025-02-19 05:55:58] [    4.696084] [    287]     0   287     3976     1696    73728        0             0 systemd-userwor
[2025-02-19 05:55:58] [    4.696683] [    288]     0   288     3976     1696    69632        0             0 systemd-userwor
[2025-02-19 05:55:58] [    4.696713] [    290]     0   290     3914     1632    73728        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696737] [    291]     0   291     3914     1632    73728        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696762] [    292]     0   292     3914     1632    73728        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696786] [    293]     0   293     3914     1664    73728        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696810] [    294]     0   294     3914     1632    77824        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696835] [    295]     0   295     3976     1696    73728        0             0 systemd-userwor
[2025-02-19 05:55:58] [    4.696859] [    298]     0   298     3914     1664    69632        0             0 systemd-nsresou
[2025-02-19 05:55:58] [    4.696884] [    308]     0   308     3976     1696    69632        0             0 systemd-userwor
[2025-02-19 05:55:58] [    4.696909] [    325]     0   325     2090     1219    49152        0             0 haveged
[2025-02-19 05:55:58] [    4.696932] [    326]     0   326     1171      832    57344        0             0 mount-dirs.sh
[2025-02-19 05:55:58] [    4.696958] [    328]     0   328     8010     2912    86016        0          -250 systemd-journal
[2025-02-19 05:55:58] [    4.696982] [    331]     0   331     9171     3155    94208        0         -1000 systemd-udevd
[2025-0 [...]

2025-02-20 21:39 UTC, Guiiix commented
I updated my net-vm to r4.3-testing and effectively, new services are present. I tried to disable ``systemd-nsresourced.service`` but it is started by systemd-nsresourced.socket and even with ``ConditionalPathExists`` and both units, it's starting anyway.

2025-02-20 21:47 UTC, marmarek commented
> `ConditionalPathExists`

typo: `ConditionPathExists`

see journalctl, maybe it will tell you why it ignored the setting
alternatively, for testing you can mask either or both units and see what happens; I expect something to fail, but it's interesting to learn what, as maybe that other thing isn't needed either ;)

2025-02-20 22:40 UTC, Guiiix commented
Oops, sorry for the typo.
Well, the reason was stupid, ``systemd-nsresourced.socket`` was starting before ``qubes-sysinit.service``... So ``/var/run/qubes-service/minimal-netvm`` was not present. :sweat_smile:
I added an ``After`` statement in the dropins and now it's not running anymore. 
Everything seem to be fine, no service failed, no strange error in the journal...

2025-02-20 22:55 UTC, Guiiix commented
When masking the service:
  * socket fails to start before the service couldn't be loaded
 
When masking the socket or both
  * no service failed nor error in the journal

2025-02-20 23:02 UTC, Guiiix commented
``systemd-userdbd`` doesn't seem necessary too

2025-02-26 10:14 UTC, ben-grande commented
Can you please document this feature in https://github.com/QubesOS/qubes-core-admin-client/blob/main/doc/manpages/qvm-service.rst

2025-02-28 14:56 UTC, Guiiix commented
Got an error about conntrack tables full today with 300MB RAM...

2025-02-28 15:10 UTC, marmarek commented
Hm, I guess the default size is chosen based on the memory mount. But it should be configurable. But still, even if we increase the limit, the question is whether there is enough RAM to store it.
Can you check `/proc/sys/net/nf_conntrack_max`? There is also `/proc/sys/net/netfilter/nf_conntrack_max`, not sure what is the relation between them - I see the same value in both. FWIW I have 2560 there on R4.2 with 400MB for sys-net.

2025-02-28 15:22 UTC, Guiiix commented
Yes I guess this is configurable but it might be hard to find a suitable value not too high as we don't have enough memory and not too low as we can have a lot of connections when running multiple qubes with network access.

On my sys-net (R4.3-current-testing repos, 325MB RAM) , I have the same value for both variables: 2048.

2025-02-28 15:28 UTC, marmarek commented
So, it's not too different from my value, yet I haven't run into such issues. Is it possible that some of your applications opens more than usual connections? You can also list what is in the conntrack table with the `conntrack -L` call, maybe that will hint what is going on (it will probably make more sens in sys-firewall, as that will see which AppVM that is, sys-net will have all connections attributed to sys-firewall's IP.